### ISSUE TITLE
Adding to conda-forge 

### ISSUE THREAD

**Issue by nicholsn** [jmkeyes/keyrings.codeartifact#5]
Hi @jmkeyes! Thanks for putting this package together. I'd like to add it to conda-forge and have a PR staged at https://github.com/conda-forge/staged-recipes/pull/28358

Can I add you as the maintainer or should I keep it under my handle?

Hope this is ok!

**Comment by jmkeyes** [comment]
Hey @nicholsn! This looks good to me!

I don't use Conda that often myself, but I'm OK with being listed as a maintainer if it'll help out.

When I've managed Conda `environment.yml` files for Python projects, I usually list the `requirements.txt` in the dependencies section with something like this:

```
name: project
...
dependencies:
  - python
  - pip:
    - -r requirements.txt
```

I do this because it keeps up to date with the project as a whole and allows for the flexibility to continue using `pip` directly.

Is that also possible with a recipe's `meta.yml`?

**Comment by nicholsn** [comment]
Great, thanks @jmkeyes! I updated the PR to list you as the maintainer.

I think for `meta.yaml` you need to list out dependencies and they need to already be available in conda-forge or another channel, so it's independent from pypi.

I've been using a package manager called [pixi](https://pixi.sh/latest/) that lets you do something similar to what you're doing by combining pypi and conda packages.  I'm looking into using CodeArtifacts with pixi and came across a [blog post](https://ericmjl.github.io/blog/2024/9/19/how-to-set-up-pixi-with-codeartifacts/) for how to set this up using your library.

It looks like [other options for keyring](https://pixi.sh/latest/advanced/authentication/#pypi-authentication) in Azure and Google are already available in conda so hopefully this will make it easier to set up!
